munich-quantum-toolkit/ddsim

src/Simulator.cpp
=> The variable isn't used afterwards and never freed.

.github/workflows/cmake.yml
This PR enables CI under Windows using Github Actions.
The Boost libraries are built once and then cached in order to reduce subsequent CI runtimes.
This PR also adds a workflow dispatch which allows to run the CI on demand from the Github Actions tab.
=> Add Windows to Github Actions CI

.github/workflows/bindings.yml, CMakeLists.txt, MANIFEST.in, pyproject.toml, setup.py
- Pruned directories from external submodules in MANIFEST.in to reduce size of sdist to below one megabyte.
- Use ninja as generator target on supported plattforms in setup.py to improve wheel build times
- Stop building wheels for python3.6 as it's eol since a couple months
=> Improve Wheel Building Process

src/PathSimulator.cpp, test/test_path_sim.cpp
When given an empty circuit. The `PathSimulator` produced a segfault due to the `root_edge` not being intialized. This PR addresses this bug.
=> 🐛 Fix segfault for empty circuit in `PathSimulator`

.git_archival.txt, .gitattributes, pyproject.toml
Following https://scikit-hep.org/developer/packaging#versioning-mediumhigh-priority, this PR adds the necessary steps to allow git archives (including the ones generated from GitHub) to also support versioning.
Based on https://github.com/cda-tum/qcec/pull/187
=> Added Support for Versioning in Archives

.github/workflows/bindings.yml
The last release builds the arm64 wheels twice.
=> Fix missing macos-x64 builds

apps/simple.cpp, include/CircuitSimulator.hpp, include/HybridSchrodingerFeynmanSimulator.hpp, include/UnitarySimulator.hpp, mqt/ddsim/bindings.cpp, mqt/ddsim/hybridqasmsimulator.py, mqt/ddsim/qasmsimulator.py, mqt/ddsim/unitarysimulator.py, src/CircuitSimulator.cpp, src/Simulator.cpp, test/python/simulator/test_standalone_simulator.py, test/python/unitarysimulator/test_standalone_unitary_simulator.py, test/test_circuit_sim.cpp, test/test_stoch_noise_sim.cpp
This PR adds the necessary changes to expose the existing approximation functionality to Python.
Changes are really minor; mostly unification of the simulator constructors.
While writing tests, I even found and subsequently fixed a bug in the implementation that prevented nodes at level 0 from being collected.
=> ✨ Expose Approximation Methods in Python

include/Simulator.hpp, mqt/ddsim/bindings.cpp, test/test_circuit_sim.cpp
This tiny little PR allows for setting the DD package tolerance for Simulators from Python by exposing a `set_tolerance(tol: float)` method in all simulators.
It also takes the opportunity and extracts some common functionality from all simulators in the Python-C++ bindings and eliminates redundant code.
As a neat side effect, the active as well as the maximum node count are exposed to Python as well.
=> ✨ Expose tolerance and node counts to Python

include/CircuitSimulator.hpp, mqt/ddsim/bindings.cpp, src/CircuitSimulator.cpp, test/python/simulator/test_standalone_simulator.py, test/test_circuit_sim.cpp
This small PR exposes the newly added expectation value functionality from the DD Package to the `CircuitSimulator` in C++ as well as Python.
This allows to compute expectation values of observables that can be specified as quantum circuits. On the Python side, Qiskit `QuantumCircuit`s can be conveniently used.
=> ✨ Expose expectation value computation from DD Package to DDSIM

.github/workflows/cmake.yml, test/python/simulator/test_standalone_simulator.py, test/python/taskbasedsimulator/test_path_sim_standalone_simulator.py
- Update QFR to include fixes for gphase
- PathSim Test does not time out anymore (fixes #211)
- Simplify approxmation test
=> Update QFR and fix two tests

apps/simple.cpp, include/HybridSchrodingerFeynmanSimulator.hpp, include/Simulator.hpp, mqt/ddsim/bindings.cpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/Simulator.cpp, test/test_circuit_sim.cpp, test/test_hybridsim.cpp
The Hybrid Schrödinger Feynman Simulator is buggy and sometimes does not terminate, see #215 
One possible reason is the previously wrong allocation of the amplitude vector vector.
Remark: Unfortunately `virtual` function cannot be templated, so there has to be this ugly work-around for the Hybrid-Schrödinger-Feynman-Simulator of creating a new and none-overloading function for its `getVector...`.
=> Possible fix for HybridSchroedingerFeynman

.github/workflows/cpp-linter.yml, .pre-commit-config.yaml
Update clang-format version for pre-commit and deactivate formatting in cpp-linter.
=> Update clang-format version for pre-commit

docs/Doxyfile, docs/source/api/ddsim.rst, docs/source/conf.py, mqt/ddsim/job.py, mqt/ddsim/qasmsimulator.py, test/python/simulator/test_qasm_simulator.py
This PR fixes the documention which currently does not include the API docs for bindings. 
The changes also omit unnecessary calls to Graphviz dot and the creation of LaTeX docs by doxygen.
Relates to #224
=> Fix Error in Docs Leading to Missing Info on Bindings

test/python/simulator/test_qasm_simulator.py
- Add test to cover parameterized gates with two targets handed to the simulator via Qiskit
=> Add test to cover parameterized gates w/ 2 targets

.gitignore, apps/simple.cpp, include/DeterministicNoiseSimulator.hpp, include/Simulator.hpp, include/UnitarySimulator.hpp, mqt/ddsim/bindings.cpp, src/Simulator.cpp, test/test_circuit_sim.cpp
- Includes improved memory management
- Adapt the simulator code
=> Upgrade MQT Core

.clang-tidy, .github/workflows/cpp-linter.yml, include/HybridSchrodingerFeynmanSimulator.hpp, src/CircuitSimulator.cpp, src/DeterministicNoiseSimulator.cpp, src/GroverSimulator.cpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/PathSimulator.cpp, src/ShorFastSimulator.cpp, src/ShorSimulator.cpp, src/Simulator.cpp, src/StochasticNoiseSimulator.cpp
- Explicit DD terminals have been replaced by nullptr
- Allows for more qubits
- Requires changes to some loops
=> No more explicit DD terminals

include/DeterministicNoiseSimulator.hpp, include/ShorFastSimulator.hpp, include/StochasticNoiseSimulator.hpp, src/ShorFastSimulator.cpp, src/StochasticNoiseSimulator.cpp
- Fix compiler warnings, mostly shadowing variables
=> Fix Compiler Warnings

src/CircuitSimulator.cpp, test/test_circuit_sim.cpp
This PR adds the non-unitary reset operation to DDSIM. 
Fixes #270
=> Add Reset Operation in Simulator

.github/workflows/bindings.yml, README.md, noxfile.py, pyproject.toml
Python 3.12 has hit RC1 and is thus ABI stable. Hence, one can start to distribute wheels for it.
This PR enables the respective support. Testing of the wheels is skipped for now, since not all dependencies are available for 3.12 (i.e., Qiskit).
=> ✨ Python 3.12 Support

docs/source/conf.py, pyproject.toml
Sphinx recommends not setting `hmtl_baseurl` so that RtD can figure it out on its own.
=> 🩹 📝 Removes the `hmtl_baseurl` setting from RtD config

apps/noise_aware.cpp, apps/simple.cpp, include/DeterministicNoiseSimulator.hpp, include/HybridSchrodingerFeynmanSimulator.hpp, include/Simulator.hpp, include/UnitarySimulator.hpp, src/CircuitSimulator.cpp, src/DeterministicNoiseSimulator.cpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/ShorFastSimulator.cpp, src/ShorSimulator.cpp, src/Simulator.cpp, src/StochasticNoiseSimulator.cpp, src/python/bindings.cpp, test/test_circuit_sim.cpp, test/test_det_noise_sim.cpp, test/test_hybridsim.cpp, test/test_path_sim.cpp, test/test_stoch_noise_sim.cpp
This PR adjusts DDSIM to the latest changes within mqt-core.
It also updates the taskflow submodule; mainly to make #301 obsolete.
=> ⬆️  Update mqt-core submodule

pyproject.toml, test/python/simulator/test_standalone_simulator.py
The newest Qiskit release introduced some new deprecations and, unfortunately, also some internal deprecation warnings that now surface in our tests and must be ignored.
This PR adjusts MQT DDSIM to these latest changes.
=> 👽 adapt to latest qiskit version

docs/source/Primitives.ipynb, src/mqt/ddsim/primitives/estimator.py, src/mqt/ddsim/qasmsimulator.py, test/python/primitives/test_estimator.py
Creating a DDSIM version of the second qiskit primitive: The "Estimator". This primitive calculates expectation values of observables with respect to the output state of a `QuantumCircuit` object.
Code is adapted from the BackendEstimator class from https://qiskit.org/documentation/stubs/qiskit.primitives.BackendEstimator.html, which in turn is a child class of the more general BaseEstimator class https://qiskit.org/documentation/stubs/qiskit.primitives.BaseEstimator.html.
=> ✨ DDSIM version of Estimator primitive

.gitmodules, .pre-commit-config.yaml, CMakeLists.txt, apps/CMakeLists.txt, cmake/ExternalDependencies.cmake, noxfile.py, pyproject.toml, src/CMakeLists.txt, src/mqt/ddsim/hybridqasmsimulator.py, src/mqt/ddsim/pathqasmsimulator.py, src/mqt/ddsim/qasmsimulator.py, src/mqt/ddsim/unitarysimulator.py, src/python/CMakeLists.txt, test/CMakeLists.txt, test/python/constraints.txt
This PR updates the mqt-core submodule and brings in some further advancements from #355.
Specifically, it switches to using `FetchContent` for obtaining `mqt-core`.
Per default, it is pointed to the vendored submodule via an overridable CMake variable.
=> ⬆️ update mqt-core

docs/source/Installation.rst, docs/source/Quickstart.rst, docs/source/Usage.ipynb, pyproject.toml, test/python/hybridsimulator/test_hybrid_qasm_simulator.py, test/python/hybridsimulator/test_hybrid_statevector_simulator.py, test/python/primitives/test_estimator.py, test/python/simulator/test_multi_registers_convention.py, test/python/simulator/test_qasm_simulator.py, test/python/simulator/test_statevector_simulator.py, test/python/taskbasedsimulator/test_path_sim_qasm_simulator.py, test/python/taskbasedsimulator/test_path_sim_statevector_simulator.py, test/python/unitarysimulator/test_unitary_simulator.py
This PR works around some of the newly introduced deprecation warnings in Qiskit 0.46.0.
Most notable, the deprecation of the `execute` method.
=> 🚨 work around new Qiskit deprecation warnings

apps/primebases.cpp, src/CircuitSimulator.cpp, test/test_circuit_sim.cpp
This tiny PR adds a header that was missing for compiling with `gcc` and removes some special handling from the times where `Barrier` Statements were still considered non-unitary.
=> 🧹 Add missing header and cleanup old code

apps/noise_aware.cpp, include/DeterministicNoiseSimulator.hpp, src/DeterministicNoiseSimulator.cpp, test/test_det_noise_sim.cpp
This PR adjust the codebase to the latest changes from mqt-core (specifically cda-tum/mqt-core#491).
Note that this merely applies the minimal changes necessary to run the project with the latest version.
A proper cleanup of the noise-aware simulators is scheduled to arrive with #321.
=> 👽 adjust to latest mqt-core changes

test/python/test_target.py
This PR removes the test workaround for the Qiskit target support. Qiskit no longer unnecessarily transpiles gates that are natively supported.
Fixes #290
=> 🩹 Qiskit now transpiles gates correctly

.pre-commit-config.yaml, pyproject.toml
This PR adds a new pre-commit check that runs Scientific Python's Repo Review and checks for the use of established best practices throughout the project.
Adding the check immediately revealed the use of some deprecated settings.
=> ✨ add sp-repo-review to pre-commit check

include/DeterministicNoiseSimulator.hpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/ShorFastSimulator.cpp, src/ShorSimulator.cpp, src/python/bindings.cpp, test/test_det_noise_sim.cpp, test/test_unitary_sim.cpp
This PR pulls in the changes from cda-tum/mqt-core#358, which considerably changes the way matrix decision diagrams are represented. Particularly, any node resembling the identity is now eliminated and only implicitly represented.
This further compacts the representation of quantum gates and makes the identity the most compact it can be---a single terminal node.
The overall performance improvements are still to be evaluated.
=> ✨ Stripping DDs of their identity

src/CircuitSimulator.cpp, src/DeterministicNoiseSimulator.cpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/PathSimulator.cpp, src/ShorFastSimulator.cpp, src/ShorSimulator.cpp, src/StochasticNoiseSimulator.cpp, test/test_circuit_sim.cpp, test/test_det_noise_sim.cpp, test/test_stoch_noise_sim.cpp, test/test_unitary_sim.cpp
This PR updates DDSIM to the latest mqt-core version that has dropped some long-overdue parameters of functions and members of classes. In particular, the operation classes no longer need the total number of qubits and the starting qubit in order to properly function.
=> ♻️ Refactor based on changes to `Operation` class in mqt-core

.github/codecov.yml, noxfile.py, pyproject.toml, test/python/constraints.txt
This PR updates the CI configuration to use uv by Astral (the creators of ruff), which is an extremely fast Python package installer and resolver, written in Rust. It is sesigned as a drop-in replacement for common pip and pip-tools workflows.
See https://github.com/astral-sh/uv
Similar to ruff, it is extremely fast and in very active development. This should speed up any of the Python-based CI runs without much confirguration overhead.
This PR refactors the `minimums` check to make use of `uv`'s `--resolution=lowest-direct" feature. This allows us to completely get rid of the `constraints.txt` file. 
Furthermore, it makes use of the new versions of `mqt-core`'s reusable workflows.
=> ✨ Adopt `uv` in CI

.clang-tidy, .cmake-format.yaml, .editorconfig, .git_archival.txt, .gitignore, CMakeLists.txt, LICENSE.md, cmake/ExternalDependencies.cmake, pyproject.toml, src/CMakeLists.txt, src/python/CMakeLists.txt, test/CMakeLists.txt
This PR updates a couple of the configuration files responsible for code formating, linting, etc.
This brings the project closer to the currently established best practises from mqt-core.
=> 🎨 Code format and linting config update

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
This PR makes use of `cibuildwheel`'s latest addition of a `build[uv]` build frontend option that uses `uv` under the hood to speed up the build process.
Furthermore, it adjusts the Windows repair command to respect namespace packages.
Before: `11h 23m 43s`, After: `10h 59m 31s`
=> ⚡🔧 Faster cibuildwheel and better Windows wheel repair

.github/workflows/update-mqt-core.yml, .gitmodules, cmake/ExternalDependencies.cmake
https://github.com/cda-tum/mqt-core was included as a submodule so far. This PR removes this submodule and uses the existing fetch content commands to include this dependency.
Furthermore, it adds a dependabot-like update workflow for the FetchContent-managed mqt-core dependency.
=> 🧱 include MQT Core via FetchContent instead of as a submodule

include/Simulator.hpp, test/test_circuit_sim.cpp
Fixes #404 
The `rootEdge` was not properly initialized, which led to `rootEdge.w.r == rootEdge.w.i == nullptr` and henceforth a nullptr dereference in the `RealNumber::val` method.
=> 🐛 properly initialize `rootEdge`

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/update-mqt-core.yml, pyproject.toml
This PR updates the MQT workflows to `v1.3`, which is the first version to offer moving minor tags that should reduce the update frequency.
Furthermore, the updated workflows combine the emulated wheel jobs to reduce overall build time and reduce the number of parallel jobs.
=> ⬆️ update mqt-workflows to v1.3 (moving tag)

cmake/ExternalDependencies.cmake, noxfile.py, pyproject.toml
This small PR updates the requirement on pybind11 to `2.13.5` which contains a fix for some relative paths that could trip up compilers.
=> ⬆️ require pybind11 >= 2.13.5

pyproject.toml, src/mqt/ddsim/__init__.py, src/mqt/ddsim/deterministicnoisesimulator.py, src/mqt/ddsim/header.py, src/mqt/ddsim/hybridqasmsimulator.py, src/mqt/ddsim/hybridstatevectorsimulator.py, src/mqt/ddsim/job.py, src/mqt/ddsim/pathqasmsimulator.py, src/mqt/ddsim/pathstatevectorsimulator.py, src/mqt/ddsim/primitives/estimator.py, src/mqt/ddsim/primitives/sampler.py, src/mqt/ddsim/provider.py, src/mqt/ddsim/qasmsimulator.py, src/mqt/ddsim/statevectorsimulator.py, src/mqt/ddsim/stochasticnoisesimulator.py, src/mqt/ddsim/target.py, src/mqt/ddsim/unitarysimulator.py, test/python/primitives/test_estimator.py, test/python/primitives/test_sampler.py
This PR (finally) enables ruff's `D` code for `pydocstyle` lint rules.
Consequently, it fixes all the resulting warnings.
Additionally, it adds rules for favoring `collections.abc` over `typing` where appropriate.
=> 🚨 enable ruff's `D` code for docstrings

.github/workflows/cd.yml, pyproject.toml
CentOS 7, which the default `manylinux2014` image is based on, reached end-of-life in June 2024.
The only meaningful platforms left that do not provide a recent enough `glibc` version are some `Amazon Linux 2` platforms, which are not really relevant for the MQT.
This PR moves the Linux wheel builds to the more recent `manylinux_2_28` images, which offers many performance improvements and optimizations.
=> 🐍⬆️ update image for Linux wheel builds to manylinux_2_28

.pre-commit-config.yaml, CMakeLists.txt, cmake/cmake_uninstall.cmake.in, noxfile.py, pyproject.toml, src/CMakeLists.txt
This PR contains a couple of assorted library improvements including touch ups on the CMake config, the mypy configuration, and the pre-commit hooks.
=> 🚸 Small library improvements

CMakeLists.txt, README.md, docs/source/Installation.rst, noxfile.py, pyproject.toml, src/mqt/ddsim/provider.py
Python 3.8 will reach end of live in October 2024.
Qiskit is already issuing deprecation warnings since a couple of releases when using it on Python 3.8.
This PR officially drops support for Python 3.8 in mqt-ddsim.
=> 🔥 drop Python 3.8 support

cmake/ExternalDependencies.cmake, include/HybridSchrodingerFeynmanSimulator.hpp, src/HybridSchrodingerFeynmanSimulator.cpp, src/PathSimulator.cpp, test/test_hybridsim.cpp, test/test_path_sim.cpp
This PR improves the error management of the HSF and the Path Simulator and makes them report a little more user-friendly error messages if certain constructs of a circuit are not supported by the simulators.
Fixes #251 and #269
=> 🚸 Improved error reporting in HSF and Path Simulator

cmake/ExternalDependencies.cmake, include/UnitarySimulator.hpp, src/CircuitSimulator.cpp, src/Simulator.cpp, src/UnitarySimulator.cpp, src/python/bindings.cpp, test/test_unitary_sim.cpp
This PR adds a dedicated DD package configuration for the unitary simulator. By increasing the sizes of the datastructures relevant for the task while shrinking all others, this should noticably improve performance for the unitary simulator.
Fixes #182
=> ⚡ dedicated unitary simulator DD package config

.github/workflows/ci.yml
This PR explicitly sets the permissions for the reusable workflows that need OIDC token permissions.
This should allow the workflows to properly work on PRs from forks.
=> 🛂 explicitly set workflow permissions to enable runs from forks
