- README.md
- apps/benchmark.cpp
- apps/simple.cpp
- include/GroverSimulator.hpp
- include/QFRSimulator.hpp
- include/ShorFastSimulator.hpp
- include/ShorSimulator.hpp
- include/Simulator.hpp
- src/GroverSimulator.cpp
- src/QFRSimulator.cpp
- src/ShorFastSimulator.cpp
- src/ShorSimulator.cpp
- test/test_fast_shor_sim.cpp
- test/test_grover_sim.cpp
- test/test_qfr_sim.cpp
- test/test_shor_sim.cpp
- Weak simulation does not work for circuits with non-unitary operations. This is now automatically considered.
- Adjusted the README
> Correct Measurement

- CMakeLists.txt
- README.md
- apps/benchmark.cpp
- apps/noise_aware.cpp
- apps/simple.cpp
- include/CircuitSimulator.hpp
- include/QFRSimulator.hpp
- src/CMakeLists.txt
- src/CircuitSimulator.cpp
- src/QFRSimulator.cpp
- src/Simulator.cpp
- test/CMakeLists.txt
- test/test_circuit_sim.cpp
- test/test_stoch_noise_sim.cpp
- Correct handling of measurements in circuits
- If circuit has measurements and classical bits, only these are returned
- If circuit has no measurements, all qubits are measured (as before)
- Removed reordering from code base
- Smaller changes to the README
Fixes #8
> All new CircuitSimulator

- .github/workflows/cmake.yml
- README.md
- ddsim.ipynb
Also install `libboost-program-options-dev` on ubuntu to test building the apps.
> Documentation on the Python bindings

- .github/workflows/bindings.yml
- CMakeLists.txt
- setup.py
- src/CMakeLists.txt
> Fixes for Apple Silicon

- .github/workflows/bindings.yml
- .github/workflows/cmake.yml
- CMakeLists.txt
- README.md
- include/HybridSchrodingerFeynmanSimulator.hpp
- pyproject.toml
- setup.py
- src/CMakeLists.txt
- src/HybridSchrodingerFeynmanSimulator.cpp
* Remove OpenMP dependency and use taskflow instead. Fixes #31
* Build Apple Silicon wheels
> Dropped OpenMP

- setup.py
Editable installs were not working anymore. This PR addresses this bug.
> 🐛 fix editable installs

- README.md
- docs/source/refs.bib
- docs/source/simulators/NoiseAwareSimulator.rst
Adding a link to the pdf of the "Noise-aware Quantum Circuit Simulation With Decision Diagrams" reference.
> adding pdf link to the references

- .pre-commit-config.yaml
- .readthedocs.yaml
- docs/source/Usage.ipynb
- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
This PR adds a new section to the docs, which shows the usage of the simulators from python in a jupyter notebook.
Thanks @burgholzer for doing this in qmap so I had it easier :)
> Added notebook of simulators to docs

- .github/release-drafter.yml
- .github/workflows/bindings.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
- .github/workflows/cpp-linter.yml
This PR introduces the following changes:
- Use mold as linker
- Remove unnecessary install step for pip3
- Caching for pip installs
- Use long options where more appropriate
- Adjust template for release-drafter
> Update Action Workflows

- test/test_circuit_sim.cpp
- Update dependency to current main branch
- Adapt tests (remove template syntax)
> Update MQT-Core Dependency

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- README.md
- docs/source/Contributing.rst
- docs/source/Development.rst
- docs/source/Installation.rst
- docs/source/Support.rst
- docs/source/index.rst
- mqt/ddsim/hybridqasmsimulator.py
- mqt/ddsim/hybridstatevectorsimulator.py
- mqt/ddsim/pathqasmsimulator.py
- mqt/ddsim/pathstatevectorsimulator.py
- mqt/ddsim/qasmsimulator.py
- mqt/ddsim/statevectorsimulator.py
- mqt/ddsim/unitarysimulator.py
- pyproject.toml
- Links to the repository not include the mqt- prefix
- Mention MQT Core instead of QFR and DD_Package
- Load MQT logo from DDSIM instead of QMAP
- Fix a few copy past errors
> Change links to repository

- include/ShorFastSimulator.hpp
- include/ShorSimulator.hpp
- src/ShorFastSimulator.cpp
- src/ShorSimulator.cpp
Include the most recent commits and adapt to the changed code.
> Update MQT Core Dependency

- mqt/ddsim/__init__.py
- mqt/ddsim/error.py
- mqt/ddsim/hybridqasmsimulator.py
- mqt/ddsim/hybridstatevectorsimulator.py
- mqt/ddsim/job.py
- mqt/ddsim/pathqasmsimulator.py
- mqt/ddsim/pathstatevectorsimulator.py
- mqt/ddsim/provider.py
- mqt/ddsim/qasmsimulator.py
- mqt/ddsim/statevectorsimulator.py
- mqt/ddsim/unitarysimulator.py
- pyproject.toml
- setup.py
- test/python/generate_benchmarks.py
- test/python/hybridsimulator/test_hybrid_qasm_simulator.py
- test/python/hybridsimulator/test_hybrid_standalone_simulator.py
- test/python/hybridsimulator/test_hybrid_statevector_simulator.py
- test/python/simulator/grover.py
- test/python/simulator/test_multi_registers_convention.py
- test/python/simulator/test_qasm_simulator.py
- test/python/simulator/test_standalone_simulator.py
- test/python/simulator/test_statevector_simulator.py
- test/python/taskbasedsimulator/test_path_sim_qasm_simulator.py
- test/python/taskbasedsimulator/test_path_sim_standalone_simulator.py
- test/python/taskbasedsimulator/test_path_sim_statevector_simulator.py
- test/python/test_provider.py
- test/python/unitarysimulator/test_standalone_unitary_simulator.py
- test/python/unitarysimulator/test_unitary_simulator.py
This PR adds a proper pytest and coverage configuration and also some further `ruff` checks and corresponding auto-fixes.
> 🐍 Update some of the Python configuration

- .pre-commit-config.yaml
- docs/source/Usage.ipynb
- pyproject.toml
- test/python/unitarysimulator/test_standalone_unitary_simulator.py
This PR adopts the new ruff formatter as a replacement for black and, in turn, also updates the ruff configuration.
> ✨ adopt ruff formatter and update ruff config

- .readthedocs.yaml
This PR adds graphviz to the RtD dependencies so that the documentation renders properly.
> 🩹 add graphviz to the RtD dependencies

- .github/codecov.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- noxfile.py
This PR updates the reusable MQT workflows to their latest version. It also makes use of explicit versioning in order to avoid surprises caused by updates in the future and to allow getting updates from dependabot.
> 👷⬆️ update reusable workflows

- docs/Development.rst
- docs/FAQ.rst
- docs/Installation.rst
This PR updates some outdated parts in the documentation that were using options and names that have either been removed or changed.
This is only a small step towards a larger documentation update that is long overdue already.
Fixes #449
> 📝 update outdated parts of the documentation

- .readthedocs.yaml
- CHANGELOG.md
- UPGRADING.md
- noxfile.py
This PR changes the test setup to not rebuild MQT Core from source. 
Related to https://github.com/munich-quantum-toolkit/qcec/issues/661
> 🎨 Do not rebuild MQT Core in tests

- CHANGELOG.md
- UPGRADING.md
This PR prepares the release of v2.0.0. 🎉
> 🔖 Prepare release of v2.0.0

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- UPGRADING.md
- pyproject.toml
See https://github.com/munich-quantum-toolkit/core/pull/1165/ for more information.
Fixes #636
> 🔥 Drop support for x86 macOS systems
